from enum import StrEnum


class UserActionType(StrEnum):
    SUBMIT = "SUBMIT"
    ACCEPT = "ACCEPT"
    SIGN = "SIGN"
    CREATE = "CREATE"


class SubmissionState(StrEnum):
    SUBMISSION_ACCEPTED = "SUBMISSION_ACCEPTED"
    SUBMISSION_STARTED = "SUBMISSION_STARTED"
    SUBMISSION_UPLOAD_MALFORMED = "SUBMISSION_UPLOAD_MALFORMED"
    SUBMISSION_UPLOADED = "SUBMISSION_UPLOADED"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    VALIDATION_EXPIRED = "VALIDATION_EXPIRED"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    VALIDATION_SUCCESSFUL = "VALIDATION_SUCCESSFUL"
    VALIDATION_WITH_ERRORS = "VALIDATION_WITH_ERRORS"
    VALIDATION_WITH_WARNINGS = "VALIDATION_WITH_WARNINGS"


class FilingTaskState(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class FilingType(StrEnum):
    ANNUAL = "ANNUAL"
